version: "3.8"
services:
  db:
    build: ./docker/db
    user: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "6432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:
